services:
    VerisureLab\Library\AAAGuardAuthenticator\Security\AAATokenAuthenticator: ~

    VerisureLab\Library\AAAGuardAuthenticator\Security\Provider\AAAUserProvider:
        arguments: ['@verisure_lab.aaa_api_client.api_client']